### ISSUE TITLE
Documentation Feature Request: can README.md have a ref to installing bower?

### ISSUE THREAD

**Issue by byuksel** [DmitryBaranovskiy/raphael#1005]
When following the instruction on README.md, 'python -m SimpleHTTPServer' gives the following error when you request 'http://localhost:8000/dev/raphaelTest.html'

127.0.0.1 - - [12/Nov/2015 12:11:21] "GET /dev/raphaelTest.html HTTP/1.1" 200 -
127.0.0.1 - - [12/Nov/2015 12:11:21] code 404, message File not found
127.0.0.1 - - [12/Nov/2015 12:11:21] "GET /bower_components/requirejs/require.js HTTP/1.1" 404 -
127.0.0.1 - - [12/Nov/2015 12:11:21] code 404, message File not found

In raphaelTest.html there is this line:
 

Can we add this line to README.md as well?

**Comment by tomasAlabes** [comment]
Done
