### ISSUE TITLE
Raphael website says site not found

### ISSUE THREAD

**Issue by ibrierley** [DmitryBaranovskiy/raphael#1019]
http://raphaeljs.com/ produces the error.

**Comment by djminkus** [comment]
I'm getting this too. I wonder if he decided to stop hosting it permanently... That would be a shame... it's really great documentation.

**Comment by ricardograca** [comment]
Interestingly accessing http://raphaeljs.com/reference.html works. I guess it must be some kind of redirection issue.

**Comment by tjcrowder** [comment]
Down for me, too, and not just the front page. I get "unresolved host." (@ricardograca Could that have been cached? By your system, or a proxy? Doesn't work for me.) http://downforeveryoneorjustme.com/raphaeljs.com says it's down for them, too.

**Comment by ricardograca** [comment]
Yeah, it was being cached. On another browser it doesn't work. Since this project seems to be nearly dead anyway I'm not sure if the website will be fixed.

**Comment by tomasAlabes** [comment]
Hi guys, could you please file the issue in https://github.com/DmitryBaranovskiy/raphaeljs.com? @DmitryBaranovskiy might take a look, I don't have permission on that repo
Thanks!

**Comment by medialabgk** [comment]
http://dmitrybaranovskiy.github.io/raphael/
