### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by stcherenkov** [DmitryBaranovskiy/raphael#1021]
DNS doesn't resolve http://raphaeljs.com/

**Comment by TimoSolo** [comment]
Very annoying... https://twitter.com/DmitryBaranovsk/status/692240837003051008
You can get the docs here: https://web.archive.org/web/20160121064823/http://raphaeljs.com/reference.html

**Comment by stcherenkov** [comment]
Thanks for the link!

There is `reference.html` in the repo that looks up to date. Maybe we should make gh-pages with it and CSS from web.archive.org?

**Comment by Alexgolshtein** [comment]
https://raphaeljscom-alexgolshtein.c9users.io/index.html

**Comment by sikuda** [comment]
http://sikuda.ru/raphaeljs.com

**Comment by tomasAlabes** [comment]
Dimitry is already looking into this. Check https://github.com/DmitryBaranovskiy/raphaeljs.com 
Thanks for the workaround.

**Comment by TimoSolo** [comment]
@tomasAlabes why close this when the website is still down? leave it open so other people dont recreate the issue </2c>
