### ISSUE TITLE
raphaeljs.com is down

### ISSUE THREAD

**Issue by LukaszGrela** [DmitryBaranovskiy/raphael#1022]
I've got this error while trying to access the raphaeljs.com

```
This web page is not available

ERR_NAME_NOT_RESOLVED
```

I was after the documentation

**Comment by TimoSolo** [comment]
you can get it at http://sikuda.ru/raphaeljs.com/
(see #1021)

**Comment by Alexgolshtein** [comment]
clone https://raphaeljscom-alexgolshtein.c9users.io/index.html

**Comment by Paraintom** [comment]
Still the case! thank you for the alternative link.

**Comment by sikuda** [comment]
And RaphaëlJs Tutorial
Author: Sebastián Gurin http://cancerbero.mbarreneche.com/raphaeltut/

**Comment by stcherenkov** [comment]
Mirror by @Alexgolshtein is down.

**Comment by tomasAlabes** [comment]
@DmitryBaranovskiy any update on this? Should we start looking for another solution? It's been a while...

**Comment by tomasAlabes** [comment]
Better than waiting: http://dmitrybaranovskiy.github.io/raphael/

**Comment by tomasAlabes** [comment]
Hmm it's still down, I'll leave it open...

**Comment by aeberlin** [comment]
Use http://dmitrybaranovskiy.github.io/raphael/, it's more reliable anyway.

GitHub will never be down permanently, while personal hosting can just go out and never come back up.

**Comment by DmitryBaranovskiy** [comment]
I do not control hosting or domain name. Therefore I am as much annoyed as you, guys. May be more, because I also receive a shitstorm of emails telling me that site is broken. :(

**Comment by TimoSolo** [comment]
:+1: thanks for explaining @DmitryBaranovskiy - who is the new owner so we can spam them instead? ;) Is it part of Sencha now?

**Comment by aarjithn** [comment]
@DmitryBaranovskiy meanwhile could you please update the site link in github to http://dmitrybaranovskiy.github.io/raphael ? I was not aware of this url until I saw in this issue.

**Comment by domino14** [comment]
still down

**Comment by bokanist** [comment]
@DmitryBaranovskiy, if it is a hosting problem, I could offer you a hosting solution free of charge. 
Thank you for the library.

**Comment by fntlnz** [comment]
The website is not down, it's just not available as a 2nd level domain at http://raphaeljs.com

It's available as a third level domain at: http://www.raphaeljs.com/

That's verifiable with dig:

```
dig raphaeljs.com
```

Tells that the 2nd level domain does not have an A entry

```
; <<>> DiG 9.8.3-P1 <<>> raphaeljs.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40545
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;raphaeljs.com.			IN	A

;; Query time: 1 msec
```


While

```
dig www.raphaeljs.com
```

tells that the third level domain does have an A entry that points to the given ip address.
```
; <<>> DiG 9.8.3-P1 <<>> www.raphaeljs.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44534
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.raphaeljs.com.		IN	A

;; ANSWER SECTION:
www.raphaeljs.com.	1701	IN	A	54.173.116.232
```


However would be great to have the first level domain available too.

**Comment by bokanist** [comment]
Thank you for your answer.

All the links I found on the net point to the second level.

By the way, as I got you, I have a question. Do you plan a SVG only version
of Raphael ?

I'm working on a seamless SVG / HTML / Canvas (webGL)  framework, that
unifies Coordinates and transformations like it was in flash.

Thank you for sharing your work. I admire people like you.

B.R.




2016-04-28 16:35 GMT+02:00 Lorenzo Fontana <notifications@github.com>:

**Comment by llamerr** [comment]
@bokanist I think I can answer your question with this link - http://snapsvg.io/about/

> Currently, the most popular library for working with SVG is Raphaël. One of the primary reasons Raphaël became the de facto standard is that it supports browsers all the way back to IE 6. However, supporting so many browsers means only being able to implement a common subset of SVG features. **Snap was written entirely from scratch by the author of Raphaël (Dmitry Baranovskiy), and is designed specifically for modern browsers (IE9 and up, Safari, Chrome, Firefox, and Opera)**. Targeting more modern browsers means that Snap can support features like masking, clipping, patterns, full gradients, groups, and more.

**Comment by caimen** [comment]
You still can't access via http://raphaeljs.com/ 

If you Google Raphael JS it takes you to that address which is failing. Most people are not realizing the site is still up. Even my old boss thought that Raphael JS was dead because of this issue.

**Comment by llamerr** [comment]
@caimen I just opened that address and was redirected to http://dmitrybaranovskiy.github.io/raphael/

**Comment by caimen** [comment]
Yeah and if you Google 'raphael js' in Firefox, then click on the link from google it will similarly fail as with Chrome.  raphaeljs.com is in some kind of DNS twilight zone.  All I can say is it's not good for the project to have an official site that is inaccessible from Google.

**Comment by kumavis** [comment]
should at least redirect to www

**Comment by DanielRuf** [comment]
It is because there is no DNS entry for the domain without www. Just add the missing DNS record and it should work.

Many websites have the same problem, try it with www.

**Comment by tomasAlabes** [comment]
As we don't know who owns raphaeljs.com (https://whois.icann.org/en/lookup?name=raphaeljs.com) and the github url is up, working and being the 1st result in google, we can close this. If someone knows or owns the domain please point it to https://dmitrybaranovskiy.github.io/raphael/

@DmitryBaranovskiy could you change the URL in the description? I don't have permission to do it.
