### ISSUE TITLE
Create custom tooltip 

### ISSUE THREAD

**Issue by princemjain** [DmitryBaranovskiy/raphael#1028]
I am trying to use rapheal.js to create some circle in my page and also trying to get a custom tool-tip on the circle.
There is a attr to circleNode called title which is used to define tool-tip. But for designing we tried using bootstrap tool-tip design but raphaeljs is not allowing to bring bootstrap in raphaeljs scope.
Following the code we are using:

`var circleNode = mapView.circle(mapLayoutObj.radius, mapLayoutObj.vertical, mapLayoutObj.nodeRadius)
    .attr({
      "stroke": menuItem.menu_color, 
      "transform": "r" + angle + " "+mapLayoutObj.radius+" "+mapLayoutObj.radius,
      "fill": menuItem.menu_color
    })

Please help us to achieve this

Thanks in advance

**Comment by tomasAlabes** [comment]
Please ask your questions in [http://stackoverflow.com/questions/tagged/raphael](http://stackoverflow.com/questions/tagged/raphael) or [https://groups.google.com/forum/#!forum/raphaeljs](https://groups.google.com/forum/#!forum/raphaeljs).
Let's keep this for issues.
Thanks
