### ISSUE TITLE
http://raphaeljs.com/ is down.  Looks like a domain issue

### ISSUE THREAD

**Issue by charleshimmer** [DmitryBaranovskiy/raphael#1029]

**Comment by Ajmariff** [comment]
+1

**Comment by sikuda** [comment]
I make a clone http://sikuda.ru/raphaeljs.com/
from https://github.com/DmitryBaranovskiy/raphaeljs.com

**Comment by tomasAlabes** [comment]
Duplicated https://github.com/DmitryBaranovskiy/raphael/issues/1022
Please search for issues before creating a new one.
Thanks.
