### ISSUE TITLE
Paper.text is very slow.

### ISSUE THREAD

**Issue by gsmlg** [DmitryBaranovskiy/raphael#1039]
`Paper.text` is very slow.
run 1000 times in chrome/firefox using 3000+ms and dead in ie

**Comment by tomasAlabes** [comment]
Please follow issues guidelines. Re-opening when new/better/appropriate info is provided.

**Comment by gsmlg** [comment]
`Paper.text` is using `Element.getBBox` get text styles.
This is very slow when creating hundreds of `text Elements`

**Comment by JohnnyLiu2** [comment]
I am facing the same problem, when I draw more than 1,000 text elements, it's very slow. Any suggestion for me?

**Comment by CottonSatyr** [comment]
I should say I have the same problem in IE11. 6 seconds in Chrome VS 280 seconds in IE 11 on ~1500 elements. Any solutions?
