### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by sureshdontha** [DmitryBaranovskiy/raphael#1041]
Hello Sir,
The http://raphaeljs.com/ site is not working. I am getting following message from from past few days.

**This site can’t be reached
raphaeljs.com’s server DNS address could not be found.
ERR_NAME_NOT_RESOLVED**

Thank you,
Suresh.

**Comment by tomasAlabes** [comment]
Duplicated. https://github.com/DmitryBaranovskiy/raphael/issues/1022
