### ISSUE TITLE
v2.1.2 branch and tag confuses bower and github 

### ISSUE THREAD

**Issue by AusIV** [DmitryBaranovskiy/raphael#1049]
It seems that Raphael has both a tag and a branch called "v2.1.2", and they point to different things. Due to a weird git configuration, this lead to us picking up the branch on a bower install, rather than the tag. Additionally, when I select the tag "v2.1.2" in the github UI, it shows the branch instead, as it assumes that you will only have one or the other. 

I'm curious if there's a reason to keep the 2.1.2 branch around, and if so, why would it not match the tag?

**Comment by tomasAlabes** [comment]
I can remove v2.1.2 branch, it's useless now. Would that be ok?

**Comment by AusIV** [comment]
That would be awesome.

**Comment by tomasAlabes** [comment]
Done
