### ISSUE TITLE
Update url on GitHub website

### ISSUE THREAD

**Issue by GloverDonovan** [DmitryBaranovskiy/raphael#1052]
Although the README.md has been changed to reflect the new address, the url on the GitHub repository itself has not been changed.

https://github.com/DmitryBaranovskiy/raphael/issues/1022#issuecomment-215446237

Ref #1022

**Comment by EskelCz** [comment]
also google keeps serving the old website :(

**Comment by amilajack** [comment]
@DmitryBaranovskiy what's the status of this?
