### ISSUE TITLE
npm repo of raphael doesn't work

### ISSUE THREAD

**Issue by sirtongster** [DmitryBaranovskiy/raphael#1055]
I did tried to install raphael repository from npm, but it doesn't install. I attached the error below:

npm ERR! git clone --template=/home/sparrow/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /home/sparrow/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-22d68e02: Cloning into bare repository '/home/sparrow/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-22d68e02'...
npm ERR! git clone --template=/home/sparrow/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /home/sparrow/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-22d68e02: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/sparrow/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /home/sparrow/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-22d68e02: github.com[0: 192.30.252.120]: errno=Connection timed out
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "raphael"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/sparrow/.npm/_git-remotes/_templates --mirror git://github.com/adobe-webplatform/eve.git /home/sparrow/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-22d68e02
npm ERR! Cloning into bare repository '/home/sparrow/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-22d68e02'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.120]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by tomasAlabes** [comment]
Worked for me.
```
...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.120]: errno=Connection timed out
...
```
Check your network.

**Comment by jannone** [comment]
For me, it installs, but it does not run:

Code:
```
var Raphael = require("raphael");
```

Result:
```
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/jannone/Documents/prj/test-spec/node_modules/raphael/raphael.min.js:1:7837)
    at Object.a (/Users/jannone/Documents/prj/test-spec/node_modules/raphael/raphael.min.js:2:21906)
    at e (/Users/jannone/Documents/prj/test-spec/node_modules/raphael/raphael.min.js:1:398)
    at Object.<anonymous> (/Users/jannone/Documents/prj/test-spec/node_modules/raphael/raphael.min.js:1:519)
    at e (/Users/jannone/Documents/prj/test-spec/node_modules/raphael/raphael.min.js:1:398)
    at /Users/jannone/Documents/prj/test-spec/node_modules/raphael/raphael.min.js:1:485
    at /Users/jannone/Documents/prj/test-spec/node_modules/raphael/raphael.min.js:1:490
    at t (/Users/jannone/Documents/prj/test-spec/node_modules/raphael/raphael.min.js:1:145)
    at Object.<anonymous> (/Users/jannone/Documents/prj/test-spec/node_modules/raphael/raphael.min.js:1:269)
    at Module._compile (module.js:541:32)
```

**Comment by aegis1980** [comment]
@jannone Did you ever resolve this? I get the same error.

**Comment by jannone** [comment]
@aegis1980 No, unfortunately...

**Comment by tomasAlabes** [comment]
Sorry guys but I can't reproduce this...do you use anything special? version of raphael?

**Comment by grimmdude** [comment]
I'm having this issue as well.  `require('raphael')` doesn't seem to be working correctly.

**Comment by grimmdude** [comment]
Can verify the error here:
https://npm.runkit.com/raphael

**Comment by tomasAlabes** [comment]
Raphael can't be used in a node env, only in browser. `document` doesn't exist in the server.

**Comment by usamatekrowe** [comment]
Try to remove:  "package-lock.json"  file first and then "npm install".
