### ISSUE TITLE
MouseMove in Opera doesn't work with vscrollbar

### ISSUE THREAD

**Issue by KAV-Invariant** [DmitryBaranovskiy/raphael#106]
Example http://raphaeljs.com/analytics.html works fine, but.
Make 2 changes: 
1) first, add big DIV - just before /body:  	div style="height:2000px"
This is to make scrollbar appear
2) in style of page, change
                margin: -125px 0 0 -400px;
to
                margin: 125px 0 0 -400px;
This is to make graph position not at the top, so that we need to scroll the scrollbar to operate with graph.
After this changes, mousemove works very strange, practically doesnt work at all (in Opera 10.10). Other browsers (even IE) hold this correctly.
It was noticed, that Opera calculates coordinates normally only when scroll bar is on top. So, if we make only step 1 (see upper) without step 2, everything will be OK unless vertical scrollbar is not on top.
Whose bug is it? Opera, Raphael or mine? :)

**Comment by tomasAlabes** [comment]
Opera using webkit now and seems to be an old issue.
