### ISSUE TITLE
Bower warning about eve short-sha

### ISSUE THREAD

**Issue by ghost** [DmitryBaranovskiy/raphael#1065]
I get the following warning each time I install raphael via bower:

```sh
bower eve#eef80ed
short-sha consider using longer commit sha to avoid conflicts
````

Would adding full `eef80ed8d188423c2272746fb8ae5cc8dad84cb1` in place of `eef80ed` here: https://github.com/DmitryBaranovskiy/raphael/blob/db2b2f2/bower.json#L6 fix the warning?

Perhaps upgrading it to the latest 0.5.0 commit: `e5743970ae26ec1e6ce099ca5e6492c727ed7147` (adobe-webplatform/eve@e5743970ae26ec1e6ce099ca5e6492c727ed7147 -> Jul 2014) instead of continue to use the existing one: `eef80ed8d188423c2272746fb8ae5cc8dad84cb1` (adobe-webplatform/eve@eef80ed -> Jan 2013) would bring some goodness as well..

**Comment by antonmarin** [comment]
composer doesn't support short sha. Update it, please ))

**Comment by tomasAlabes** [comment]
Updated in 55ee142

**Comment by antonmarin** [comment]
Is it merged to master?
