### ISSUE TITLE
Demo Angry Birds Clone - file not found

### ISSUE THREAD

**Issue by stranskyjan** [DmitryBaranovskiy/raphael#1070]
Not a big issue, but the icon looked very nice and I was curious what it is :-)
http://dmitrybaranovskiy.github.io/raphael/angry.html
Thanks for this great project
Jan

**Comment by tomasAlabes** [comment]
I can't find the link in the doc for that

**Comment by stranskyjan** [comment]
Hi Tomas,
sorry for not complete information. The link is not from documentation, it is from the main page [1], section demos, the very last link/image
cheers
Jan

[1] http://dmitrybaranovskiy.github.io/raphael/

**Comment by DmitryBaranovskiy** [comment]
This demo never were published. Basically, it was a box2d port on Raphaël.
