### ISSUE TITLE
.path() 

### ISSUE THREAD

**Issue by lkcode666666** [DmitryBaranovskiy/raphael#1078]
I'm sorry to add an issue but i don't how to do it~
when I use .path()  I know it works when it looks like this: .path('M 10,10 L 20,20);
but in my js file,I set
```js
var a=10;
blah.path('M a,10 L 20,20');
```
it doesn't work though i USE " ,it doesn't work too! do you have some good ideas?

**Comment by DmitryBaranovskiy** [comment]
```js
var a=10;
blah.path('M ' + a + ',10 L 20,20);
```

**Comment by GoToLoop** [comment]
```js
let a = 10;
blah.path(`M ${a},10 L 20,20`);
```

**Comment by lkcode666666** [comment]
Thank for you your help! I'm so happy that it works !  : ) 
|
|
|




At 2017-03-09 16:25:56, "Dmitry Baranovskiy" <notifications@github.com> wrote:

var a=10;
blah.path('M '+ a +',10 L 20,20);
