### ISSUE TITLE
Use tag not supported

### ISSUE THREAD

**Issue by AndyOGo** [DmitryBaranovskiy/raphael#1080]
I want to use some Icons from an existing SVG-Icons-Sprite by utilizing SVG's `<use>` tag.
Unfortunately  this does not seem to work.

**Comment by DmitryBaranovskiy** [comment]
Not a bug

**Comment by AndyOGo** [comment]
@DmitryBaranovskiy 
Why? It's a super useful SVG feature.
Doesn't VML support it?
