### ISSUE TITLE
SVG to PNG in Safari/Chome IOS

### ISSUE THREAD

**Issue by dume234** [DmitryBaranovskiy/raphael#1081]
Hi - The output svg of Raphael JS is different for Safari and Chrome mobile hence I face an issue when I export it as the converter from svg to png doesn't support this particular format. Is there are any work around?

For the Desktop Chrome I use the following libs/js syntax and it works fine.

`var innerSVG = canvasCollage.innerHTML;

        var fixedSVG = svgfix(innerSVG);
        canvg(data.canvasOutputId, fixedSVG, {
            renderCallback : function() {
                //to something
            }
        });` 

*svgfix - http://nerdyjs.com/script/345449
*canvg - http://canvg.github.io/canvg/canvg.js

Any suggestion would be much appreciated. Thanks.

**Comment by KingGeneral** [comment]
have you try to do "svg" to "canvas" to "png" work ???
