### ISSUE TITLE
How to combine Raphael.js with Sketch.js?

### ISSUE THREAD

**Issue by sjorsvanheuveln** [DmitryBaranovskiy/raphael#1083]
I want to use the drawing properties of sketch.js together with raphael. However Raphael takes over the canvas and disallows using sketch. How can I overcome this problem. I was thinking of saving the SVG in a js variable and then using the svg as a background image in sketch. Is this the way to go or can this be done in a simpler fashion.

**Comment by tomasAlabes** [comment]
Maybe you'd be better posting this in SO, as I'm not familiar with Sketch.js.
Closing it as no one responded in almost 2 years.
Thanks
