### ISSUE TITLE
Is there Foreign Object extension for raphael js?

### ISSUE THREAD

**Issue by jpatel3** [DmitryBaranovskiy/raphael#1085]
In order to add HTML element in Raphael Js, we need to use [ForeignObject SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) element. is there any known extension for it?

**Comment by tomasAlabes** [comment]
Nope, as it's not in VML, it's not in Raphael (accidental rhyme).

**Comment by ralexrdz** [comment]
> In order to add HTML element in Raphael Js, we need to use [ForeignObject SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) element. is there any known extension for it?

found any workaround?

**Comment by ibrierley** [comment]
I would use snap.svg Raphaels sister library. It's generally compatible, but as its focused on SVG it doesn't have the same restrictions.
