### ISSUE TITLE
Reference to Raphael-Playground is invalid

### ISSUE THREAD

**Issue by papanito** [DmitryBaranovskiy/raphael#1091]
The link to the Raphael-Playground is invalid and points to a non-existing page. 
[raphael/CONTRIBUTING.md](https://github.com/DmitryBaranovskiy/raphael/blob/master/CONTRIBUTING.md)

**Comment by tomasAlabes** [comment]
[raphael/CONTRIBUTING.md](https://github.com/DmitryBaranovskiy/raphael/blob/master/CONTRIBUTING.md) exists. Let me know if you're referring to something else.
