### ISSUE TITLE
Fix Raphael version information

### ISSUE THREAD

**Issue by MarkMaldaba** [DmitryBaranovskiy/raphael#1095]
Currently:
* [The Raphael website](dmitrybaranovskiy.github.io/raphael/) lists the latest release as v2.2.1
* [The Github repository](https://github.com/DmitryBaranovskiy/raphael/releases) lists the latest release as v2.2.7
* In both of the above places, and in the master branch, the internal version number reported by Raphael is v2.2.0

Please can you update the code and any official builds to use the correct version number.  Also, can you clarify what the latest official build is - is it 2.2.1 or 2.2.7 (or 2.2.0)?

**Comment by tomasAlabes** [comment]
I updated the website so that it points to Releases, so I don't have to maintain it manually. Also updated the version in the banner, that one I'd like to remove but I'm not sure of the copyright stuff. I can take it out if @DmitryBaranovskiy is ok with it.
Thanks for taking the time to check the versions.

**Comment by MarkMaldaba** [comment]
Thanks, Tomas - that's great!

However, there is one place you missed, which is the internal Raphael version number.  This is in [raphael.core.js on line 70](https://github.com/DmitryBaranovskiy/raphael/blob/v2.2.8/dev/raphael.core.js#L70)

Can you update the 2.2.8 release to include the correct version number, or will that have to wait until 2.2.9?

```` R.version = "2.2.0";````

**Comment by tomasAlabes** [comment]
Thanks again @MarkMaldaba, it's in too many places 🤦‍♂️... 
I might wait for a while for more PRs before publishing it. Is it bothering you in some particular way?

**Comment by MarkMaldaba** [comment]
The main issue for me was not knowing what the 'official' version was, due to the contradiction between Github and the website.  We didn't want to use a beta release in production.

This issue has been resolved by your clarifications, above.

The only other thing from our point of view, is that we display the version number in our credits page, so until the internal version number is fixed we will be showing misleading information.  However, I don't think it's that important, so happy to wait for it.

Do you have a release script or set of instructions that you follow, and has it been updated to include the various version-number updates?  It's great that it's fixed, but it would be even more great if steps have been taken to avoid it getting missed again in the future. ;-)
