### ISSUE TITLE
I am getting Raphael not defined error 

### ISSUE THREAD

**Issue by ymihir** [DmitryBaranovskiy/raphael#1098]
I am creating SPFx web part for SharePoint. I am trying to generate a chart using [TreantJS](http://fperucic.github.io/treant-js/). TreantJS using Raphael js to build the components. 
I am always getting `Raphael not defined` error even i try with multiple ways.
1. I have loaded the script with [SPComponentLoader](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom.md#reference-jsom-imperatively) method.
2. I have loaded with [$.getScript](https://api.jquery.com/jquery.getscript/) method.
In both ways, I have tried to print the output in console. with first method it is coming as 
![r1](https://user-images.githubusercontent.com/7568187/41864698-75f184fc-78c8-11e8-9f3a-6a4f1365da57.PNG) with the second method it is coming as undefined. 
What is wrong here?

**Comment by tomasAlabes** [comment]
Sorry but please take it to the TreantJS maintainers. Or ask in SO.
Thanks
