### ISSUE TITLE
Website link to "Free Icons" -> 404

### ISSUE THREAD

**Issue by ssteinerx** [DmitryBaranovskiy/raphael#1100]
Link "Free Icons" right side main navigation on: 

http://dmitrybaranovskiy.github.io/raphael/

to:

http://dmitrybaranovskiy.github.io/icons/

Results in 404 Not Found error in browser.

**Comment by tomasAlabes** [comment]
Added the icons back. I had to reverse-engineer the web archive but I think most of it is there.
Thanks for the shout out.
