### ISSUE TITLE
Error: <path> attribute transform: Expected transform function

### ISSUE THREAD

**Issue by ajay-verma-01** [DmitryBaranovskiy/raphael#1103]
Hi,

I am getting following error when using raphael.js.
I didn't get the cause of the issue. Could you please help. I am using v2.1.0
---------
Error: <path> attribute transform: Expected transform function, "m,0.9101334025,0…".
w | @ | Raphael.js:2499
-- | -- | --
  | S.attr | @ | Raphael.js:2638

**Comment by tomasAlabes** [comment]
Please add more information and try [Raphael in Stackoverflow](https://stackoverflow.com/questions/tagged/raphael) first. If an issue is found please post it here.
Thanks
