### ISSUE TITLE
Raphael 2.2.8 is doing "unsafe-eval", 2.2.7 isn't doing this

### ISSUE THREAD

**Issue by le0pard** [DmitryBaranovskiy/raphael#1110]
After update to patch version Raphael 2.2.8 system stop to work. Looks like library at version 2.2.8 start doing some `eval`. `unsafe-eval` disabled by our CSP don't allow this, so we are back to version 2.2.7, which doesn't have this problem. 

I think next time better at least add this breaking changes to https://github.com/DmitryBaranovskiy/raphael/blob/master/history.md#228

**Comment by tomasAlabes** [comment]
That was because the dev versions of the files included sourcemaps (using eval). I removed those in v2.3.0 so it should be fixed
