### ISSUE TITLE
"arrow-end" throw an Error: <path> attribute d: Expected number, “….68028259277344CNaN,NaN,NaN,NaN,…”

### ISSUE THREAD

**Issue by hadasmaimon** [DmitryBaranovskiy/raphael#1128]
Library: "raphael": "^2.2.8"

**Summary:** 
all work as expected apart from the console error

**Description:**
I want to render a line with an arrow end,
but when adding "arrow-end" attribute, it throw an Error: "attribute d: Expected number, "….68028259277344CNaN,NaN,NaN,NaN,…".
weirdly when adding "arrow-start" attribute there is no error

I tried already to change the stroke-width, it didn't help

**This is the code:**
http://jsfiddle.net/fzjc81ym/ (don't see an error in console through the js fiddle, only in my repository)

```
this.canvas = Raphael('grid', '100%', '100%');

drawLine(this.canvas, path1, duration, arrowAtrr, color, strokeDasharray, strokeWidth, arrowend).then(() => this.resolve(item, callback))

const drawLine = (canvas, pathStr, duration = 1000, attr = arrowAtrr, color = Color.GREEN, strokeDasharray = '-', strokeWidth = 4, arrowend = "block-wide-long") => {
    return new Promise((resolve) => {
        attr.stroke = color;
        attr['stroke-dasharray'] = strokeDasharray;
        attr['stroke-width'] = strokeWidth;
        attr['arrow-end'] = arrowend
        var guidePath = canvas.path(pathStr).attr({ stroke: 'none', fill: 'none' });
        var path = canvas.path(pathStr).attr({ stroke: 'none', fill: 'none' });
        var totalLength = guidePath.getTotalLength(guidePath);
        var startTime = new Date().getTime();
        var intervalLength = 25;

        var intervalId = setInterval(function () {
            var elapsedTime = new Date().getTime() - startTime;
            var thisLength = elapsedTime / duration * totalLength;
            var subPathStr = guidePath.getSubpath(0, thisLength);
            attr.path = subPathStr;
            path.attr(attr)
            path.animate(attr, intervalLength);

            if (elapsedTime >= duration) {
                clearInterval(intervalId);
                resolve();
            }

        }, intervalLength);

    });
}
```

![image](https://user-images.githubusercontent.com/40765442/105187896-f82f9c80-5b3b-11eb-8d71-d2947942566d.png)

Any idea how to solve that error?

**Comment by ibrierley** [comment]
Where's the rest of the code? :)

**Comment by hadasmaimon** [comment]
oh ok, added (edited the issue description)

**Comment by ibrierley** [comment]
I suspect you don't want to animate arrow-end attribute.

**Comment by hadasmaimon** [comment]
I want to animate the arrow line ( I don't think we need animation on the arrow-end )
![Edit fiddle - JSFiddle - Code Playground](https://user-images.githubusercontent.com/40765442/105250803-05bc4500-5b83-11eb-8a66-e1087803fd43.gif)

**Comment by hadasmaimon** [comment]
any idea how to solve it?

**Comment by ibrierley** [comment]
Can I just check I understand the problem correct...does it all work as
expected apart from the console error ?

**Comment by hadasmaimon** [comment]
yes, exactly.
thanks for the answer!

**Comment by ibrierley** [comment]
It's difficult without knowing the full spec, but personally I would optimise it to this...

http://jsfiddle.net/se29wkom/

I haven't completed all the attr vars, but hopefully you get the idea.

**Comment by ibrierley** [comment]
Ignore, there's a bug in that....

**Comment by ibrierley** [comment]
Interesting, looks a bit more fiddly than I thought. Seems to happen with a
combo of 'arrow-end' and 'stroke-width', I'm guessing Raph adds those
behind the scenes and tries to animate them even if not included in the
exact animate call, causing the issue. Will have a ponder.

**Comment by hadasmaimon** [comment]
wow appreciating the efforts you made, 
Do you think for a solution?

**Comment by ibrierley** [comment]
Tbh I can't think of a very non-hacky way of getting around it (eg having a separate arrow end that's transformed or something). At this point, I'd consider moving to Snap (it's pretty compatibly with Raph), although it doesn't include arrow ends as default (there are examples out there, eg below), it's a lot more flexible (you can call functions every frame to build an animation).

Example http://jsfiddle.net/4cvaM/9/

**Comment by hadasmaimon** [comment]
oh ok,
I want to try moving to Snap, but I see that
https://www.npmjs.com/package/snapsvg - (is it the correct link of the library?)
was Last publish 4 years ago...
compared to Raphael
https://www.npmjs.com/package/raphael
which was Last publish 1 year ago...

**Comment by hadasmaimon** [comment]
A solutions:
in my case, the arrow line was smaller than the arrow-end triangle,
so I set the min size of the path to be 11
`var subPathStr = guidePath.getSubpath(0, Math.max(11, thisLength));`
