### ISSUE TITLE
element.mousemove

### ISSUE THREAD

**Issue by GoldWood2000** [DmitryBaranovskiy/raphael#1141]
![image](https://user-images.githubusercontent.com/52521162/186624950-bbe985f5-2656-4190-a7e0-1d491ebc097b.png)
Hello, I have a problem, that is, the red circle part on the picture is the position where my mouse is placed, and then the x, y are obtained, and the character a==1 is displayed, but why is the position of x and y not my mouse? The location and the gap is so big, which puzzles me

**Comment by ibrierley** [comment]
Hard to tell without seeing any code.

**Comment by GoldWood2000** [comment]
> 没有看到任何代码很难说。

<img width="445" alt="image" src="https://user-images.githubusercontent.com/52521162/186651076-4422c8d6-f4c0-497a-a837-a9f78e4c1421.png">
My need is to show and hide a text at the position of the mouse

**Comment by ibrierley** [comment]
Is the tip_text inside some svg or other container or element that may be scaled or translated ?

**Comment by GoldWood2000** [comment]
> Is the tip_text inside some svg or other container or element that may be scaled or translated ?

<img width="1638" alt="image" src="https://user-images.githubusercontent.com/52521162/186653994-1ab83874-cc8f-4743-959c-20cd18e6ceab.png">

yes, inside an svg,The first red circle part is the position where my mouse is placed on the line, but the obtained x and y are indeed very different from the mouse position. It is expected that a==1 will be displayed in the first red circle.

**Comment by ibrierley** [comment]
Ok, so you probably need to either move the text outside of the elements that are transforming it, or transform the x,y with the with the inverse of the transform that's affecting it. It's a bit fiddly that stuff (Snap.svg may be slightly easier Raphaels sister package, but you will likely still have to get a bit messy if you can't draw it outside of the elements affecting it).

**Comment by GoldWood2000** [comment]
> Ok, so you probably need to either move the text outside of the elements that are transforming it, or transform the x,y with the with the inverse of the transform that's affecting it. It's a bit fiddly that stuff (Snap.svg may be slightly easier Raphaels sister package, but you will likely still have to get a bit messy if you can't draw it outside of the elements affecting it).

hi, I would like to ask setViewBox when it is dragged for the first time, but the second drag does not start from the position of the first drag, but from the position of the first rendering, what properties do I need to set?
