### ISSUE TITLE
getBBox throws blocking error in Firefox 

### ISSUE THREAD

**Issue by janoserdelyi** [DmitryBaranovskiy/raphael#21]
Firefox 3.0.11
i am loading both prototype and jquery libraries prior to loading raphael 0.8. jquery is in noconflict mode. i don't know if any of that matters, but providing it just in case.

i'm using the uncompressed raw file for ease of hunting down issues.

when i load up 0.8 in FF i get this error:

Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMSVGLocatable.getBBox]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: http://local.www.sqibl.com/js/raphael.0.8.js :: anonymous :: line 1135"  data: no]
Source File: http://local.www.sqibl.com/js/raphael.0.8.js
Line: 1135

when i click through, the offending line it takes me to is actually line 1136 which is:
var bbox = this.node.getBBox();

**Comment by 1Cr18Ni9** [comment]
If you want _**getBBox**_ to be functional the svg element should be visiable.
Try This: [JSFiddle](https://jsfiddle.net/Cheery/9qvkxp8v/).

**Comment by rasalshri** [comment]
hi

**Comment by rasalshri** [comment]
If you are using html template and css, javascript then ,
remove class with property display:none  above the  map class and add some new class
after loading or executing getbox function attach that removed class(having property display: none) through javascript.
it works for me , and simple and easy thanks.
it is simple and quick solution

**Comment by nikober** [comment]
> If you want _**getBBox**_ to be functional the svg element should be visiable.
> Try This: [JSFiddle](https://jsfiddle.net/Cheery/9qvkxp8v/).

Still error
[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: https://fiddle.jshell.net/Cheery/9qvkxp8v/show/ :: window.onload :: line 48"  data: no]
