### ISSUE TITLE
enhancement: allow filling an object with a pattern

### ISSUE THREAD

**Issue by kenyee** [DmitryBaranovskiy/raphael#283]
This is possible in SVG:
http://www.w3.org/TR/SVG/pservers.html#Patterns

but the closest thing I can find in Raphael is filling w/ a gradient.
Would be nice to be able to specify a few generic patterns (crosshatch, checkboard, etc.) or be able to define a pattern that can be passed in for the fill attribute...

**Comment by subhog** [comment]
So, a few years passed. I really need this feature, and I'm not targetting anything below IE 11. Is there intention to move this forward, or is there any official fork intended for full-featured support of modern browsers?

**Comment by tomasAlabes** [comment]
Raphael's motivation is to offer cross-browser support for vectorial graphics and this includes SVG and VML for old IEs. So no, we will not remove the support for VML.
You can use Dmitry's [Snap.svg](snapsvg.io/) for svg only features.

**Comment by subhog** [comment]
Thanks, that's exactly what I need. I just found out about Snap from StackOverflow. It should be probably mentioned in the readme of Raphael. The first place where I looked at is the "related projects" list, so I propose the addition: https://github.com/DmitryBaranovskiy/raphael/pull/932
