### ISSUE TITLE
Cannot read property 'x' of undefined when using getPointAtLength()

### ISSUE THREAD

**Issue by jarmo** [DmitryBaranovskiy/raphael#284]
Sometimes i'm getting this error when trying to use getPointAtLength():
    Cannot read property 'x' of undefined

Chrome shows following stacktrace:
    Uncaught TypeError: Cannot read property 'x' of undefined  raphael.js:3026
    getLengthFactory  raphael.js:3026
    elproto.getPointAtLength  raphael.js:3053

I can't reproduce it every time, but it seems to happen on Chrome, IE8 and Firefox.

Solution would be to add +1 to lineLength like this:
    var lineLength = lastLine.getTotalLength();
    if (lineLength == 0) {
      return;
    }
    try {
      lastPoint = lastLine.getPointAtLength(lineLength);
    }
    catch (e) {
      lastPoint = lastLine.getPointAtLength(lineLength + 1);
    }

Also it would be great if lastLine.getPointAtLength(0) would work. I guess it's related with #128.

**Comment by flyher** [comment]
@ro0t 
hi, thank you for your answer! it's help me.
