### ISSUE TITLE
colorwheel & colorpicker only work when appended to the body

### ISSUE THREAD

**Issue by webxl** [DmitryBaranovskiy/raphael#477]
Tested on latest chrome, firefox and ie8. I copied the colorpicker example and added my own divs to the content div, then passed in references to those divs to the colorpicker/wheel "constructors": http://jsfiddle.net/webxl/zmARH/

I had to inline the plugins to get them working in IE, but they are the same ones from raphaeljs.com

**Comment by suhajdab** [comment]
bump

**Comment by DmitryBaranovskiy** [comment]
Colorwheel and colorpicker are not parts of the library. They just a demo.
