### ISSUE TITLE
raphael breaks if loaded via require-js.

### ISSUE THREAD

**Issue by iwyg** [DmitryBaranovskiy/raphael#524]
Raphael also breaks if requires merely existent on the page. If `require` is not `undefined`  (and in case requirejs is loaded, require is defined),  `eve` won't be added to the global scope.

**Comment by toorshia** [comment]
I don't use require or any other kind of library, just pure, vanilla JS - and I still get "eve not defined" issue with 2.2.X https://github.com/toorshia/justgage/issues/249

**Comment by tomasAlabes** [comment]
Updated eve in 55ee142. Could you re-check? 
I used dev/index.html as a global lib and it worked...

**Comment by toorshia** [comment]
Still the same - eve not defined. 

http://justgage.com/test/raphael-2-issues/html/adaptive-size-2.2.3.htm

Using 2.2.0 works though:

http://justgage.com/test/raphael-2-issues/html/adaptive-size-2.2.0.htm

**Comment by tomasAlabes** [comment]
It's your code, not raphael's which is throwing the error. Eve is inside raphael and not exposed to you.
You can use the raphael.no-deps.js (just fixed) where eve is a dependency of raphael, so you can have eve defined for you and for raphael, and use it outside raphael.

**Comment by toorshia** [comment]
Oh, so eve not being exposed anymore is the culprit :) Good to know, thanks!

**Comment by tomasAlabes** [comment]
The idea is to load raphael without leaking any other variable or library into your window or rjs context.
With no-deps you explicitly define eve as your dependency and share it with raphael.

**Comment by alzuma** [comment]
+1

**Comment by D252874** [comment]
@tomasAlabes how do I expect to do that i am getting the same error when using angular-justgage and it breaks with the eve is undefined.

**Comment by anhle1476** [comment]
In my case (Raphael 2.1.0), the `define` method in `define("eve", [], function () { return k; })` might be conflicted with the `define` method in Monaco Editor's loader.js
