### ISSUE TITLE
wrong position in ie7 when rotate image

### ISSUE THREAD

**Issue by lloydzhou** [DmitryBaranovskiy/raphael#612]
I have run this code in ie 7, the get wrong position, but running ok in other browser.

var degree1 = 0.001;
var src1 = document.getElementById("handle").src;
var R = Raphael("holder", 590, 550),
handle = R.image(src1, 70, 36, 408, 408);
handle.transform('r' + degree1);

I think this is a floating-point overflow problem, so I suggest to be changed the code 

<code>
return rad * 180 / PI% 360;
-->
return Math.round ((rad * 180 / PI% 360)* 1000) / 1000;
</code>

in file raphael.js line 517.
and the line 513, 506 should be be the same.

**Comment by cameronjacobson** [comment]
I was able to confirm that the suggested change does fix this issue for ie5, ie7, and ie8.  It appears only the last 3 decimal places affect the result, so perhaps it's overkill to reduce all the way to 3 decimal places.

```
 return 0.000990013774108022 // fails
 return 0.000990013774108 // works
```

**Comment by tomasAlabes** [comment]
Thanks to both :D
