### ISSUE TITLE
2.1.0: Paper.setViewBox()'s "fit" parameter, if set to true, is mistranslated in terms of the underlying "preserveAspectRatio" SVG attribute value

### ISSUE THREAD

**Issue by mklement0** [DmitryBaranovskiy/raphael#649]
`true` should translate to "none" (i.e., no preservation of aspect ratio, stretching/shrinking to fill available space - assuming that was the intent of this parameter value - not clear from the documentation), whereas it currently translates to "meet", which is _not a valid value_ .

Different browsers deal with this invalid value differently:
- iOS 6.01, Chrome 23.0.1271.97, and Firefox 17.0 effectively act as if "xMidyMid meet" had been specified; i.e., they DO preserve the aspect ratio and _center_ the result - an option that `setViewBox()` doesn't even expose.
- Android browsers, by contrast, do seem to act as requested (no preservation of aspect ratio; content stretches/shrinks to fill the container).

By contrast, specifying "false" for `fit` presumably acts as intended (though the exact intended behavior is not clear from the documentation): aspect ratio is preserved and the result is placed in the top left corner.

Workaround - SVG ONLY:

Assign the correct value to the `preserveAspectRatio` SVG attribute directly.
For instance, if `p` is your Raphael paper, call the following after having called `setViewBox()` with `fit` set to `true`:

```
p.canvas.setAttribute('preserveAspectRatio', 'none');
```

Incidentally, this approach also allows you to specify values not currently exposed by `setViewBox()`.
For instance, if you wanted to preserve the aspect ratio and _center_ the result (without clipping), invoke the following:

```
p.canvas.setAttribute('preserveAspectRatio', 'xMidYMid meet');
```

See http://www.w3.org/TR/SVG11/coords.html#PreserveAspectRatioAttribute for all possible values.

P.S.: Sadly, irrespective of this bug, even with `preseveAspectRatio` set to the valid value `none`, not all SVG-capable browsers act the same; see http://jsfiddle.net/mklement/7rpmH/

**Comment by Jakobud** [comment]
Is there ever going to be an official update to this so that new versions can be pushed to CDNs, etc?
