### ISSUE TITLE
paper.text(x,y,text) creates <tspan> element with "doubled" dy value.

### ISSUE THREAD

**Issue by Siyfion** [DmitryBaranovskiy/raphael#772]
In `raphael.js` on lines `6352 - 6354`:

```javascript
var bb = el._getBBox(),
  dif = a.y - (bb.y + bb.height / 2);
dif && R.is(dif, "finite") && $(tspans[0], {dy: dif});
```

I can reproduce the issue whereby the value of `bb` is calculated as:
```javascript
height: 0
width: 0
x: 0
y: 0
```

`a.x = 65` and `a.y = 65`, resulting in a caluculated `dy` value of `65`, which essentially doubles the y offset for the given `<tspan>`.

In `_getBBox()` the value of `this.node.style.display` is `""` and `this.node.getBBox()` returns the object seen above.

**Comment by tomasAlabes** [comment]
Let's move the discussion to 491. They have a couple of workarounds working.
