### ISSUE TITLE
Gradients become black in some cases

### ISSUE THREAD

**Issue by sebas2day** [DmitryBaranovskiy/raphael#781]
Tested browser: Chrome
### Raphael version 2.1.0
The gradients become black when there are parentheses in the url. 

In SVG it will create an attribute like this:
`fill="url(http://www.example.com/page/?param=(parentheses)#222342-_7FFF7F-_159607)"`

Using apostrophes around the url will fix the problem.

Here is a patch:
```
3877c3877
<     			fill: "url(#" + id + ")",
---
>     			fill: "url('#" + id + "')",
3884c3884
<     			fill: "url(" + document.location + "#" + id + ")",
---
>     			fill: "url('" + document.location + "#" + id + "')",
```

### Raphael version 2.1.2:
The gradients become black by default when there is a base-tag set in the head:
`<base href="http://www.example.com/" />`
This is a known issue in the SVG specification: https://bugzilla.mozilla.org/show_bug.cgi?id=652991

Although using the full url like before does fix this.

**Comment by tomasAlabes** [comment]
57b62b1 try to fix this. Could you confirm it?
