### ISSUE TITLE
Slowdown with drag events on touch devices

### ISSUE THREAD

**Issue by forsdahl** [DmitryBaranovskiy/raphael#816]
Drag events seem to cause a slowdown on touch devices after being fired a couple of times. For each fired drag event dragging gets a bit slower.
Can be reproduces for example in the Graffle demo (http://raphaeljs.com/graffle.html) with an iPad with Safari by first dragging an element and noting the lag (first drag doesn't have much lag), then tapping an element ~10-20 times (tapping seems to trigger all drag start/move/end events) and then dragging the same element again. After tapping/dragging an element enough times dragging slows to a crawl.
The same test also causes a slowdown on Android with Chrome (at least on a Nexus 4) but not on desktop browsers (tested with Firefox and Chrome on Windows).

**Comment by florin-draghici** [comment]
Seems like this changes is made in c47c077368c1113e1ed653376415961749de5466, can you close this?
