### ISSUE TITLE
set.getBBox() works incorrectly if the set contains empty sets

### ISSUE THREAD

**Issue by rodweb** [DmitryBaranovskiy/raphael#823]
`getBBox()` acts weirdly when trying to calculate a bounding box for a set containing an empty set:
```js
var set = paper.set();
set.push(paper.circle(10,10,10));
```
`set.getBBox()` acts correctly now:
```js
{
  height: 20,
  width: 20.02983784606284,
  x: -0.01491892303142095,
  x2: 20.01491892303142,
  y: 0,
  y2: 20
}
```
Now let's add an empty set:
```js
set.push(paper.set());
```
And here it is:
```js
{
  height: NaN,
  width: NaN,
  x: -0.01491892303142095,
  x2: NaN,
  y: 0,
  y2: NaN
}
```
Seems like it happens because the empty set bounding box looks like this:
```js
{
  height: -Infinity,
  width: -Infinity,
  x: Infinity,
  x2: -Infinity,
  y: Infinity,
  y2: -Infinity
}
```
and somewhere in the calculating we get `NaN`. Not sure if it's a real bug, but I think there should be at least a workaround for this.

**Comment by tomasAlabes** [comment]
@rodweb could you confirm #899 works?
Leaving the PR for the issue.
