### ISSUE TITLE
raphael is improperly AMD-ified

### ISSUE THREAD

**Issue by aaronshaf** [DmitryBaranovskiy/raphael#831]
If one is using requirejs / r.js with a configured baseUrl, the 'eve' module is sought at ```[baseUrl]/eve```, which is non-existent. 

```eve``` should be delivered as a separate file and then given a relative reference, e.g. ```'./eve'```

**Comment by EthanCai** [comment]
+1

**Comment by tomasAlabes** [comment]
Small example? PR?
Thanks

**Comment by tomasAlabes** [comment]
Using webpack amd.
