### ISSUE TITLE
Some important SVG attributes cannot be applied.

### ISSUE THREAD

**Issue by danielgindi** [DmitryBaranovskiy/raphael#871]
You need to add these to the "availableAttrs" map:

    'direction':'ltr',
    'writing-mode':'lr',
    'unicode-bidi':''

**Comment by tomasAlabes** [comment]
No response, closed.

**Comment by danielgindi** [comment]
Sorry! Didn't see the response...
No there aren't equivalents, but in VML the rtl stuff just work automatically much better.
I actually have my own version of Raphael now, with the support for Bidi, and with removed support for VML.... As these browsers are not in use anymore

**Comment by tomasAlabes** [comment]
No worries. But we can't add anything to raphael that is not present in vml, the whole idea of the library is to abstract both of the formats. Anyway I'm glad you got it working with your own version.

**Comment by danielgindi** [comment]
Thank you :-) Great job!
