### ISSUE TITLE
ember-cli eve is not defined 

### ISSUE THREAD

**Issue by Tamiyadd** [DmitryBaranovskiy/raphael#890]
Hi
i'm developing an ember app using ember-cli and i'm trying to use Raphael.js but when i put it in my page with

    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>

it will return

    Uncaught ReferenceError: eve is not defined 

i read that Raphael.js have problem with RequireJS, could be related?

someone have used it successfully?

thanks a lot

**Comment by gonvaled** [comment]
Any updates?

**Comment by jakedavidson** [comment]
This is still a problem.

**Comment by tomasAlabes** [comment]
Anyone has a sample Ember app to test the problem? I created the "mdreizin-master" branch with some changes made in a PR related to how the different parts of the library were consumed.
If someone can test it with the branch and/or give a sample app to check it, it would be appreciated.

**Comment by WooDzu** [comment]
Hi @tomasAlabes 
I tried the branch with my app but unfortunately it fails with the same error.
I'll try and put together a base ember-cli repo with Raphael.

**Comment by WooDzu** [comment]
The problem is actually gone with Raphaël 2.1.4
For anyone using morris.js with ember-cli, just update via bower which will pull the latest version of Raphael
`bower update morris.js`

**Comment by tomasAlabes** [comment]
Cool. Closing this issue then.

**Comment by WooDzu** [comment]
:+1: there was another one #918
