### ISSUE TITLE
getBBox of text returns 0... when text is empty

### ISSUE THREAD

**Issue by LiamKarlMitchell** [DmitryBaranovskiy/raphael#900]
Example
````
var text = paper.text(100,100, '');
if (text.getBBox().x === 0) {
  console.log('text bbox x is 0? ');
}
````

I understand that there is no content but shouldn't the x of the bounding box be 100? and the x2 be 100 giving a width of 0. (similar for y). It seems to me the bounding box is wrong.

Looking at elproto.getBBox and getPath it seems that elproto._getBBox is where it happens.
elproto._getBBox uses this.node.getBBox() which is native code.

Something like this seems to sort it out.
````
    elproto._getBBox = function () {
        if (this.node.style.display == "none") {
            this.show();
            var hide = true;
        }
        var bbox = {};
        try {
            bbox = this.node.getBBox();
        } catch(e) {
            // Firefox 3.0.x plays badly here
        } finally {
            bbox = bbox || {};
            // does not take rotation/transform into consideration
            if (bbox.x === 0 && this.attrs.x !== 0) {
              bbox.x = this.attrs.x;
            }

            if (bbox.y === 0 && this.attrs.y !== 0) {
              bbox.y = this.attrs.y;
            }
        }
        hide && this.hide();
        return bbox;
    };
````

Please correct me if I am wrong in my understanding of how these bounding boxes should work.

Thanks

**Comment by neojski** [comment]
[Native code seems to behave this way](http://jsfiddle.net/pg2w6oL8/6) but I don't know whether this is expected or not.

**Comment by tomasAlabes** [comment]
We need to follow how svg works...sorry guys...
