### ISSUE TITLE
Animation stop, when we change tabs

### ISSUE THREAD

**Issue by sirsquall** [DmitryBaranovskiy/raphael#902]
Hi,

I don't know why, but I have an animation who is running perfectly (thanks Raphaël), but when I switch tab on the browser, the animation is stopped. Any one have an idea why ? And how can I disable this behaviour ?

Thanks

**Comment by tomasAlabes** [comment]
Raphael uses the [requestAnimationFrame API](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) for animations, is the most performant (and correct) way of doing it.
If you really need that you could do it the old way with setInterval...
