### ISSUE TITLE
SVG output doesn't set xlink namespace, causing invalid xml

### ISSUE THREAD

**Issue by winfinit** [DmitryBaranovskiy/raphael#905]
when converting SVG to canvas, if xlink namespace is not present, and any xlink: nodes are present, error occurs. most people adding a "pre processing" of created SVG to add xlink namespace, however i don't really see a reason why not include it as part of raphael, and avoid hacks.

sample error returned from **libxml**:
```
namespace error : Namespace prefix xlink for href on use is not defined
```

**Comment by tomasAlabes** [comment]
Closed per #906
