### ISSUE TITLE
Why does Raphael need to be registered in global context ? 

### ISSUE THREAD

**Issue by krampstudio** [DmitryBaranovskiy/raphael#917]
At the end of the file dev/raphael.core.js, we have the following code 

```
 // EXPOSE
// SVG and VML are appended just before the EXPOSE line
// Even with AMD, Raphael should be defined globally
oldRaphael.was ? (g.win.Raphael = R) : (Raphael = R);
```

I have a use case (I know it's not usual) where I may have 2 versions of Raphael loaded into the same page. I though using AMD I would be able to use Raphael but this comments seems to say the opposite. Why is it necessary to have R in the global context with AMD and is there a way to get rid of that ?

**Comment by tomasAlabes** [comment]
Now raphael should be global only if not used in an amd/commonjs manner.
