### ISSUE TITLE
ember-cli Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by givanse** [DmitryBaranovskiy/raphael#918]
In Ember CLI, If I import the library within the body, I get:

    Uncaught TypeError: Cannot read property 'on' of undefined

The error does not appear if I import from the header.

Might be related to [issues#890](https://github.com/DmitryBaranovskiy/raphael/issues/890)

**Comment by jhenley45** [comment]
Experiencing this as well. Any updates here or possible workarounds?

**Comment by WooDzu** [comment]
Same for me, Crases on:

```js
    eve.on("raphael.remove", stopAnimation);
```

**Comment by gonvaled** [comment]
Same for me!

**Comment by hellbeast92** [comment]
and for me!

**Comment by tomasAlabes** [comment]
Closing as it seems to be fixed in v2.1.4 (#890)
