### ISSUE TITLE
Chrome animate 

### ISSUE THREAD

**Issue by sirsquall** [DmitryBaranovskiy/raphael#924]
Hi,

I have some statics spots images.

```javascript
 this.paper.image('img/balls/spot.png', ...
```
And over I'm animating some svg to put in front of the spots.

```javascript
 .animate({ transform: 'S1T' + x + ' ' + y, }, 1 , 'easeInOut', ...
```

And only in chrome some statics spots disapear when the animation start and end, each time one of the image move to their correct spot.

This issue is only with the lastest chrome version the 39, before the animation worked well.

Here you have the fiddle: http://jsfiddle.net/SSJJT/82/

**Comment by tomasAlabes** [comment]
Closing as it seems to be an old chrome issue.
