### ISSUE TITLE
Problem animating curves in v2.1.2

### ISSUE THREAD

**Issue by arqex** [DmitryBaranovskiy/raphael#925]
Hi!

Thanks for this great library. I've been developing some curve animations using v2.1.0 and everything was right, but when I updated to v2.1.2 the curves become straight angles while animating.

v2.1.0 Curves animation ok
http://jsfiddle.net/marquex/xztfchc9/19/

v2.1.2 Curves become angles :/
http://jsfiddle.net/marquex/puba0x0k/1/

Any idea?

Cheers,
Javi

**Comment by cameronjacobson** [comment]
It appears v2.1.3 has fixed this issue.

**Comment by tomasAlabes** [comment]
Ran it in v2.2.0 and it was fixed.
