### ISSUE TITLE
publish npm package

### ISSUE THREAD

**Issue by theofidry** [DmitryBaranovskiy/raphael#931]

**Comment by wburgers** [comment]
You can use the bower package...
bower.io

**Comment by theofidry** [comment]
Yeah, but I'm already using Composer and npm and adding yet another package manager for just one package is just really annoying. Considering that the process to publish a npm package is almost the same as a Bower one and that it's really a fast thing to do, It really just helps other people : they are given the choice to not have to install Bower if they are not using it and using another package manager.

**Comment by wburgers** [comment]
I agree, it is indeed better.
Too bad this project is not really active :-(

**Comment by tomasAlabes** [comment]
I contacted the authors of the [current](https://www.npmjs.com/package/raphael) raphael npm package and kindly asked them to update it. I will publish one if I don't have any response.
You didn't need me for this guys...
Cheers

**Comment by tomasAlabes** [comment]
Done. Have fun!

**Comment by theofidry** [comment]
Thanks @tomasAlabes . We did not do it ourselves since we are not the maintainers, neither collaborators :)

**Comment by tomasAlabes** [comment]
I was talking about the e-mail :)
Anyway I learned a bit more about npm so I'm glad I did it :D
