### ISSUE TITLE
window.Element broken

### ISSUE THREAD

**Issue by legendar** [DmitryBaranovskiy/raphael#934]
see commit 69097d567136e752705b2854dda4cf9e9423d5b7
there should be coma after closing bracket for getRealNode function

**Comment by TheCloudlessSky** [comment]
:+1:

**Comment by conslo** [comment]
so this breaks a *LOT* of stuff, and it's a pretty simple fix, bump please?

**Comment by legendar** [comment]
pull request https://github.com/DmitryBaranovskiy/raphael/pull/936

**Comment by tomasAlabes** [comment]
Done. Thanks.
