### ISSUE TITLE
'size' is undefined - IE8

### ISSUE THREAD

**Issue by westonganger** [DmitryBaranovskiy/raphael#935]
I am getting the following error on IE8

'size' is undefined Line 1 Char 91726

Could anyone tell me how to patch it

**Comment by TheCloudlessSky** [comment]
Can you please provide a sample? What version of Raphael are you using?

**Comment by westonganger** [comment]
I am using v2.1.3. I cant provide a sample unfortunately. But I do know that it works in v2.1.1 the only reason I am upgrading is because the images in the drawing are not showing in the correct position in 2.1.1 on IE8.

**Comment by westonganger** [comment]
I could include a specific portion if you know what I need to look for or grab

**Comment by TheCloudlessSky** [comment]
OK - first run your app using the unminified version so you can get a better line number. Then debug the problem from your app and see if you can try and make a reproducible sample. Check out [JSFiddle](http://jsfiddle.net/) for an easy playground to make samples.

**Comment by westonganger** [comment]
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; InfoPath.3; MS-RTC LM 8)
Timestamp: Wed, 4 Feb 2015 02:11:21 UTC

Message: 'size' is undefined
Line: 8125
Char: 9
Code: 0
URI: XXXX/js/raphael-2.1.3.js

**Comment by westonganger** [comment]
it seems to be that on line 8128 on master should be change from 
     scale: size 
to
     scale: paperSize
to use the changed variable name on line 8110

**Comment by TheCloudlessSky** [comment]
Confirmed. This bug was introduced in 5f08cf50e5d6a852f8bc40310b2cdc85bafd5b87 late last year. I'll make a PR to fix this.

/cc @tomasAlabes
