### ISSUE TITLE
Insert image as background

### ISSUE THREAD

**Issue by Vizzielli** [DmitryBaranovskiy/raphael#941]
Edit: solved.

By using paper.image().

Thanks, good script!

**Comment by Vizzielli** [comment]
I've tried with this:

var background = map.rect(0, 0, 500, 500);
background.attr({fill: 'paper.image("img/worldmap.jpg", 0, 0, 500, 500)','stroke-width': '0',opacity: '100'}).data({'id': '1'});

Result: black image. with absolute url, same result.

**Comment by ajozwik** [comment]
Please close issue
