### ISSUE TITLE
"paper.circle.data" not working, can only use "paper.getById.data" (examples with fiddle)

### ISSUE THREAD

**Issue by KSoto** [DmitryBaranovskiy/raphael#943]
This bit of code should be working:

`//Draw:`
`var c = paper.circle(100, 100, 20)`
	         `.data("x",100)`
             `.id = "circle";`

`//Output:`
    `console.log("data is = ", paper.getById("circle").data("x"));`
`//Outputs undefined`

(See fiddle: http://jsfiddle.net/HkNgT/12/ )

In order to get this to work, I can't use **"paper.circle.data.."** I have to use **"paper.getById(..).data"** instead, like this:

`//Draw:`
`var c = paper.circle(100, 100, 20)`
            ` .id = "circle";`
`paper.getById("circle").data("x",100);`
	        
`//Output:`
`    console.log("data is = ", paper.getById("circle").data("x"));`
`//Outputs 100`

(See fiddle: http://jsfiddle.net/HkNgT/13/ )

**Comment by sikuda** [comment]
First: c.data('x')
Second: c.node is DOM element inside html for understanding
