### ISSUE TITLE
website download link says 2.1.2, but points to 2.1.3

### ISSUE THREAD

**Issue by cameronjacobson** [DmitryBaranovskiy/raphael#945]
At `http://raphaeljs.com/` the download link says it's pointing at v2.1.2, but is currently pointing at v2.1.3.

**Comment by tomasAlabes** [comment]
I need @DmitryBaranovskiy help here.

**Comment by jerone** [comment]
And now it's 2.1.4 while it says 2.1.2.

**Comment by tomasAlabes** [comment]
Issues should be added to https://github.com/DmitryBaranovskiy/raphaeljs.com
Thanks!

**Comment by jerone** [comment]
https://github.com/DmitryBaranovskiy/raphaeljs.com/pull/6
