### ISSUE TITLE
stroke-dasharray="0" breaks solid paths in FF 37.0+

### ISSUE THREAD

**Issue by datalus** [DmitryBaranovskiy/raphael#946]
Testing SVG paths with stroke-dasharray set to "" or "none" results in the attribute having the "0" value which breaks paths in Firefox's current beta & developer channels. Not sure if Mozilla will resolve this on their end before FF 37.0's release, or if this is intended behavior going forward.

Right now, my hack to fix this in my own code is to just use a space, since the raphael source code does not map " " to 0.

**Comment by tzimmermann** [comment]
Good to see others have run into this, too! I believe FF 37 is diverging from the SVG spec there and have filed a bug with Mozilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1149516

**Comment by projectvalis** [comment]
i just noticed similar wonky behavior using FF37 on my project page here:

http://www.projectvalis.com/pv_wp/

load the same page in a different browser and things work as expected.
