### ISSUE TITLE
Element.glow ignores {opacity: 0}

### ISSUE THREAD

**Issue by spookylukey** [DmitryBaranovskiy/raphael#968]
`Element.glow({opacity: 0})` (which is useful in the context of later animating the glow) behaves the same as `Element.glow({})`. It's easy to see why:

https://github.com/DmitryBaranovskiy/raphael/blob/master/raphael.js#L4185

    opacity: glow.opacity || .5,

It should instead be checking for something like `glow.opacity == null`

**Comment by spookylukey** [comment]
Actually I think it should be:

    opacity: glow.opacity === undefined ? 0.5 : glow.opacity

**Comment by GoToLoop** [comment]
Other alternatives:  :D  

* `opacity: glow.opacity != null? .5 : glow.opacity;`
* `opacity: glow.opacity || .5;`

**Comment by tomasAlabes** [comment]
f7744d0e44e9ef13ddab2a53eb14b16d8c875ddc fixes this.
Thanks!
