### ISSUE TITLE
Include eve in distribution tarballs

### ISSUE THREAD

**Issue by MarkMaldaba** [DmitryBaranovskiy/raphael#971]
Currently the release tarballs (e.g. https://github.com/DmitryBaranovskiy/raphael/releases/tag/v2.1.4) do not include the source code for Eve - they just contain an empty 'eve' directory.

Please could you update the release process so that it pulls Eve into the eve directory when these tarballs are created, so that the full source-code is distributed with the release.

Currently, anyone who manages their third-party tools using the vendor-branch method, as we do, has to hunt around the Eve repo to find the exact branch to download, which is a pain.

Given its small size and the tight-coupling, Eve should be part of the distribution.  I believe this should be easy to do in Github as there are plenty of other projects that include their dependencies in this way.

**Comment by tomasAlabes** [comment]
Now eve is inside the dev/ folder, and 2 versions of raphael available, one with and another one without eve.

**Comment by MarkMaldaba** [comment]
Great - thank you!

I was expecting a sub-module or a build-time inclusion rather than adding it direct to the repo, but whatever works best for you. :-)

**Comment by tomasAlabes** [comment]
I had to include it because I needed to modify the source of eve to make it work with raphael and amd.

**Comment by MarkMaldaba** [comment]
Fair enough - whatever works.
