### ISSUE TITLE
TypeError: R.safari is not a function

### ISSUE THREAD

**Issue by pvuk** [DmitryBaranovskiy/raphael#980]
I copied raphael.js, demo-print.css, demo.css in project under views folder in eclipse when I open below url I got error "TypeError: R.safari is not a function" in console of firebug.

http://localhost:8080/RaphaelDemo/views/australia.html

Error is occurred continuously "TypeError: R.safari is not a function" when I move the cursor on the map. 
Source link is http://raphaeljs.com/australia.html

![screenshot 67](https://cloud.githubusercontent.com/assets/3636151/9057165/a5e69958-3ab5-11e5-8783-78bca2208545.png)

**Comment by tomasAlabes** [comment]
R.safari is not part of raphael anymore, and I don't have access to the raphael site to correct what version of raphael it is using.

**Comment by joannesalfa** [comment]
I would like to know the alternatives of r.safari and r.popup in recent version of Raphael.JS, thanks!

**Comment by tomasAlabes** [comment]
It was removed because it work-arounded a bug in safari. That bug is not there anymore so the function is not needed.
