### ISSUE TITLE
ID collision causes gradients to fail.

### ISSUE THREAD

**Issue by dpcouch** [DmitryBaranovskiy/raphael#982]
With multiple instances of Raphael canvases on a page, every so often you there can be a collision when the element.ID matches. 

This causes an issue in webkit browsers when applying linear gradients. The issue is it applies attributes to the first linear gradient it finds with the ID, leaving the other (duplicate) definition attributeless. Because of the way webkit seems to work, it gets the last definition, which doesnt contain the attribute.

A quick fix is to change the code to generate a random id (line 6394) instead:
```
/*\
             * Element.id
             [ property (number) ]
             **
             * Unique id of the element. Especially usesful when you want to listen to events of the element, 
             * because all events are fired in format `<module>.<action>.<id>`. Also useful for @Paper.getById method.
            \*/
            this.id = guid();
            node.raphaelid = this.id;
            this.matrix = R.matrix();
            this.realPath = null;
```
```
function guid() {
    function s4() {
        return Math.floor((1 + Math.random()) * 0x10000)
          .toString(16)
          .substring(1);
    }
    return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
      s4() + '-' + s4() + s4() + s4();
}
```

**Comment by tomasAlabes** [comment]
Added in https://github.com/DmitryBaranovskiy/raphael/commit/b15a86d8f3a3784d81de3e38c9a853f263b9b60e
Thanks for the suggestion.
