### ISSUE TITLE
Unable to use master branch with npm/browserify

### ISSUE THREAD

**Issue by dpogue** [DmitryBaranovskiy/raphael#984]
Trying to use the raphael.js or raphael-nodeps.js with npm & browserify from the master branch of the repo results in an error:
require('raphael-core') cannot be found

**Comment by tomasAlabes** [comment]
3236fa65d7efd9a894dd3134074b8503214c40df This corrects raphael.amd.js to be used with AMD loaders such as browserify.
I've tried it myself but could you please confirm the fix? Thanks.

**Comment by tomasAlabes** [comment]
Saw your other PR, so I guess it worked.

**Comment by dpogue** [comment]
Oops, sorry, yes the raphael.amd.js file works. Thanks :)
