### ISSUE TITLE
TypeError: b.on is not a function

### ISSUE THREAD

**Issue by leonsp** [DmitryBaranovskiy/raphael#987]
I'm including minified Raphael 2.1.4 in my Meteor 1.1.0.3 app by placing it in the client/ subdirectory.

In the browser web console, I see this error:

    TypeError: b.on is not a function  raphael.2.1.4.min.js:10:18173

My motivation for including Raphael 2.1.4 is to use the JustGage library, which depends on it. JustGage bundles Raphael 2.1.0, which had more issues, but 2.1.4 is down to just the error message above.

Meteor bundles jQuery 1.11.2.

How can I get past this error message?

**Comment by tomasAlabes** [comment]
I'm not familiar to Meteor nor JustGage, but I would start using the non-minified version of Raphael to know what's causing the error. Then check what it could be.

**Comment by leonsp** [comment]
When I swap in the full Raphael, I get this error:

    TypeError: eve.on is not a function raphael.js:5216:4

This is the code on line 5216:

    eve.on("raphael.remove", stopAnimation);

I do see the function declared on line 185 of raphael.js

**Comment by martin-svk** [comment]
I have the same problem. I am loading `Raphael` as an npm module via `import Raphael from 'raphael'`.
Had to swap with `2.1.0` to get rid if this error.

**Comment by mrthebunny** [comment]
I encountered the same problem while trying to load Raphael in an Electron app's renderer process. I was able to fix the problem by following this tip from here:
http://grokbase.com/t/gg/raphaeljs/125a06s2y7/eve-is-not-defined

Add the following line in raphael.js after the eve function declaration:

```javascript
        eve = function (name, scope) {
        // ...
        };

    // added to put eve into global scope
    // cf: 
    window.eve = eve;
```

**Comment by tomasAlabes** [comment]
Now with v2.2.0? With webpack I think some distribution issues should've been solved.

**Comment by tomasAlabes** [comment]
Dead thread, reopen if it can be reproduced.
