### ISSUE TITLE
npm install is not working

### ISSUE THREAD

**Issue by izyl** [DmitryBaranovskiy/raphael#993]
Hello,

when i run : "npm install raphael"
it gives me :

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\[USER_DIR]\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:adobe-webplatform/eve.git C:\[USER_DIR]\AppData\Roaming\npm-cache\_git-remotes\git-github-com-adobe-
webplatform-eve-git-7396a03e

However I can install eve separetely

**Comment by tomasAlabes** [comment]
Works for me... did you try in another machine?

**Comment by jgrigonis** [comment]
This doesn't work for me. I get an error:

npm ERR! git clone git://github.com/adobe-webplatform/eve.git Cloning into bare repository '/home/apache/.npm/_git-remotes/git-github-com-adobe-webplatform-eve-git-94ad9f3f'...

**Comment by jgrigonis** [comment]
It works on Mac, but not on CentOS 6.7

**Comment by americoneto1** [comment]
it´s possible to change eve dependency to get by NPM registry instead of github? It'll resolve this issue when we work with private npm registries

**Comment by tomasAlabes** [comment]
Although the eve repo has a package.json, I couldn't find the registration of it... We are stuck with the url for now...
@DmitryBaranovskiy can you register eve in npm? or is it by other name?

**Comment by serganus** [comment]
same issue, eve remote git error. Pls add eve to npm
