### ISSUE TITLE
Browserify + Raphael npm package + IE8 = problems

### ISSUE THREAD

**Issue by terox** [DmitryBaranovskiy/raphael#995]
Hello everybody,

I found that the package of ```raphael``` in npm is not updated. There are problems when you use it in conjunction with Browserify + IE8. The IE8 console throws the following error when ```initWin``` function is called:
```
 'styleSheets' is null or not an object
```
We can find this function in VML module: https://github.com/DmitryBaranovskiy/raphael/blob/master/dev/raphael.vml.js#L928-L948.

**How I "patched" the problem**

Old ```package.json```:
```json
"dependencies": {
  "raphael": "^2.1.4"
}
```
Patched ```package.json```:
```json
"dependencies": {
  "raphael": "git://github.com/DmitryBaranovskiy/raphael.git#757b828560efad603dfe8d369b5c6c12da4e2bd1"
}
```
**Solution**:
I think that the solution is update the npm package to lastest version, to avoid the above fix.

I hope that it helps

**Comment by tomasAlabes** [comment]
NPM package is already updated.
