### ISSUE TITLE
rect.clone doesn't copy rounded corners

### ISSUE THREAD

**Issue by kinsxkins** [DmitryBaranovskiy/raphael#996]
Hello,
I invoke rect.clone() to create a new rect and the new rect object's attrs rx and ry are copied, but its html element is: rx="0" ry="0".

I found that the package of raphael "ignore" the two attributes:
 case "rx":
                        if (att == "rx" && o.type == "rect") {
                            break;
                        }
 case "ry":
                        if (att == "ry" && o.type == "rect") {
                            break;
                        }
So I changed it:
 case "rx":
                        if (att == "rx" && o.type == "rect") {
                        	node.setAttribute(att, value);
                            break;
                        }

Do you have a better idea? Thank you.

**Comment by kyleschlosser** [comment]
I ran into this as well, and noticed that on 2.1.0 it does not seem to happen. Are you going to submit a pull request for your modification?

**Comment by kinsxkins** [comment]
No, I'm not gonna submit a pull request for my modification.
