### ISSUE TITLE
Gradient and document.location.origin in Firefox

### ISSUE THREAD

**Issue by Dodotree** [DmitryBaranovskiy/raphael#998]
document.location.origin fails with 'undefined' and a broken URL is created

Can you please add this line to the addGradientFill  function:

       var url_origin = ( typeof document.location.origin == 'undefined' )?  
            document.location.protocol+'//'+document.location.host :
            document.location.origin;
before:
        $(o, {
            fill: "url('" + url_origin + document.location.pathname + "#" + id + "')",
            opacity: 1,
            "fill-opacity": 1
        });

to fix this problem?

**Comment by tmirun** [comment]
Guy thank for solve this error  =)

I dont know if we have the same version of firefox, but in my firefox document.location.origin show as string 'null'

so this is code for my firefox version:

var url_origin = (document.location.origin == 'null') ? 
document.location.protocol+'//'+document.location.host : document.location.origin;

**Comment by ipetropolsky** [comment]
@Dodotree try the fix from https://github.com/DmitryBaranovskiy/raphael/pull/1030
